services:
  - type: web
    name: face-emotion-recognition
    runtime: python                   # ✅ correct key
    buildCommand: pip install -r requirements.txt   # ✅ tells Render to install dependencies
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
